import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import styles from '@/styles/styles.module.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className={styles.navbar}>
      <Link href="/" className={styles.navbarBrand}>Home</Link>
      <ul className={styles.navbarNav}>
        <li className={styles.navItem}>
          <Link href="/pages/ayuda" className={styles.navLink}>Ayuda</Link>
        </li>
        <li className={styles.navItem}>
          <Link href="/pages/sesion" className={styles.navLink}>Sesion</Link>
        </li>
      </ul>
    </nav>
        {children}
        </body>
    </html>
  )
}